name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v
        with:
          java-version: '11.0.22'
          distribution: 'temurin'
      - name: Build
        run: make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: "59aad4bd31a3727727476485d78c8d74764875e776665505e87b9ea682171b2d"
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
          coverageCommand: make report
          debug: true
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
